"""
Export AI power-demand model scenarios to an Excel workbook for review.

This is an OUTPUT artifact. It RUNS model.py (the actual model) and writes the
resulting year-by-year tables to .xlsx so the scenarios are viewable in Excel.

  python research/export_model_scenarios_xlsx.py

IMPORTANT ON ARCHITECTURE: the model LOGIC lives in model.py (Python), not in any
spreadsheet. The input Excel (Token_and_Data_Build_Out_v4_2.xlsx) is only the
token-demand data the model reads; it is NEVER modified by this script. This
workbook is the model's OUTPUT, regenerable any time by re-running the command.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

_REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO))
import model  # noqa: E402  (path injected above)

OUT = _REPO / "research" / "power_model_scenarios_2026-06-23.xlsx"

# Columns to dump per scenario (FLOPs diagnostics are 0 in token-basis scenarios).
COLS = [
    "gross_tokens_T", "fleet_eff_idx", "avg_n_active_b", "flops_per_day",
    "net_compute_demand_T", "demand_gw", "supply_gw", "gap_gw",
    "cumulative_power_grid_capex_b",
]


def _summary_row(df):
    s = model.gap_summary(df)
    return {
        "peak_gap_gw": round(s["peak_gap_gw"], 1),
        "peak_year": s["peak_gap_year"],
        "balance_year": s["balance_year"],
        "overshoot_year": s["overshoot_year"],
        "cum_power_grid_capex_T_2042": round(s["cumulative_capex_2042_b"] / 1000.0, 2),
        "demand_gw_2042": round(float(df.loc[2042, "demand_gw"]), 0),
    }


def main():
    tok = model.build_token_demand(scenario="Base")

    # All four scenarios run through the SAME model.py; only the opt-in toggles differ.
    scen = {
        "Committed Base": model.build_macro_gap(tok),
        "FLOPs Basis (ITEM 8)": model.build_macro_gap(tok, use_flops_demand=True),
        "Retirement 0.20 (ITEM 9)": model.build_macro_gap(
            tok, capacity_retirement_rate=0.20),
        "FLOPs + Retire 0.20": model.build_macro_gap(
            tok, use_flops_demand=True, capacity_retirement_rate=0.20),
    }

    with pd.ExcelWriter(OUT, engine="openpyxl") as xw:
        # README sheet — explains what this workbook is.
        pd.DataFrame({"AI Power-Demand Model -- scenario outputs": [
            "Generated by research/export_model_scenarios_xlsx.py from model.py.",
            "OUTPUT ONLY. The model logic lives in model.py (Python), not this file.",
            "Input data = Token_and_Data_Build_Out_v4_2.xlsx (the token demand curves).",
            "ITEM 8 = FLOPs-native demand basis (tokens x 2N) + model-mix routing.",
            "ITEM 9 = tunable capacity retirement dial (plateau <-> cliff).",
            "Both default OFF; committed base is byte-identical (332.4 GW @ 2029).",
            "Full walkthrough: research/model_corrections_2026-06-23.md",
        ]}).to_excel(xw, sheet_name="README", index=False)

        # Summary sheet — one row per scenario.
        pd.DataFrame(
            {name: _summary_row(df) for name, df in scen.items()}
        ).T.to_excel(xw, sheet_name="Summary")

        # Side-by-side demand_gw across scenarios.
        compare = pd.DataFrame(
            {name: df["demand_gw"].round(1) for name, df in scen.items()})
        compare.index.name = "year"
        compare.to_excel(xw, sheet_name="Demand GW compare")

        # Full per-scenario detail sheets (Excel caps sheet names at 31 chars).
        for name, df in scen.items():
            df[COLS].round(4).to_excel(xw, sheet_name=name[:31])

        # Explicit tokens -> FLOPs -> power chain (FLOPs basis), the 'pure power pull'.
        f = scen["FLOPs Basis (ITEM 8)"]
        chain = pd.DataFrame({
            "tokens_per_day_T": f["gross_tokens_T"].round(1),
            "avg_N_active_B": f["avg_n_active_b"].round(0),
            "FLOPs_per_token": (2.0 * f["avg_n_active_b"] * 1e9),
            "FLOPs_per_day": f["flops_per_day"],
            "fleet_TFLOP_per_W": [model.tflop_per_w_for_year(y) for y in f.index],
            "power_GW": f["demand_gw"].round(0),
        })
        chain.index.name = "year"
        chain.to_excel(xw, sheet_name="Tokens to FLOPs to Power")

    print("Wrote", OUT)


if __name__ == "__main__":
    main()
